# **Introdução ao Python**

Vamos conhecer os seguintes conceitos iniciais:

*   Variaveis
*   Imprimir na tela
* Operações Matemática
* Arredondamento
* Função input
* Listas
* Diciopnários
* Dataframes
* Bibliotecas

## **Variáveis, print e arredondamento**

In [ ]:
disciplina          = "Estatística"   # String (palavra/frase)
quantidade_alunos   = 49              # Int (número interiro)
quantiade_aprovados = 37              # Int (número interiro)
media_geral         = 7.5             # Float (número real)

#taxa_aprovacao      = round((quantiade_aprovados/quantidade_alunos)*100,1)

taxa_aprovacao_decimal      = quantiade_aprovados/quantidade_alunos
taxa_aprovacao_percentual   = round(taxa_aprovacao_decimal*100, 1)

print(taxa_aprovacao_decimal)
print(taxa_aprovacao_percentual, "%")

print(f"A taxa de aprovação da disciplina {disciplina} é: {taxa_aprovacao}%")

0.7551020408163265
75.5 %
A taxa de aprovação da disciplina Estatística é: 75.5%

## **Interagindo com Pytyhon: input e Listas**

In [ ]:
nome = input("Qual seu nome?")

n1 = float(input("Digite sua nota 1:"))
n2 = float(input("Digite sua nota 2:"))
n3 = float(input("Digite sua nota 3:"))

Qual seu nome?Jonathan
Digite sua nota 1:5.2
Digite sua nota 2:6.3
Digite sua nota 3:8.7

In [ ]:
lista_notas = [n1, n2, n3]

soma = sum(lista_notas) #A função 'sum' soma o valor dos objetos que estão dentro da lista
qtade_notas = len(lista_notas)  #A função 'len' conta quantos objetos que estão dentro da lista

media = soma/qtade_notas

print(soma)
print(qtade_notas)
print(f"A média das notas é {media:.2f}")

20.2
3
A média das notas é 6.73

In [ ]:
import numpy as np

media_lista = np.mean(lista_notas)
print(f"A média das notas é {media_lista:.2f}")

A média das notas é 6.73

In [ ]:
"""
PROBLEMA: Calcular a n3 para aprovação, dados
a nota 1, nota2 e média mínima para aprovação

"""

# COLETAR INFORMAÇÕES INICIAIS
media_apr = float(input("Qual é a média para aprovação?")) # média mínima
nota1 = float(input("Qual foi a nota na prova 1?"))        # nota 1
nota2 = float(input("Qual foi a nota na prova 2?"))        # nota 2

# PROCESSAMENTO DOS DADOS
nota3 = media_apr * 3 - nota1 - nota2

# IMPRIMIR O RESULTADO
print("A nota necessária na avaliação 3 é:", round(nota3, 2))
print(f"A nota necessária na avaliação 3 é: {nota3:.1f}")

Qual é a média para aprovação?6.0
Qual foi a nota na prova 1?2.5
Qual foi a nota na prova 2?4.9
A nota necessária na avaliação 3 é: 10.6

**PROBLEMA 2**: Informar o preço de custo para um usuário conhecendo o preço de venda e a margem de lucro.

In [ ]:
# 1º PASSO: ENTRADA DOS DADOS

preco_venda = 2.59
margem_lucro = 35 #em valor percentual

# 2º PASSO: PROCESSMAENTO DOS DADOS

preco_custo = preco_venda / (1 + margem_lucro/100)

# 3º PASSO: IMPRIME OS RESULTADOS

print(f"O preço de custo é: R${round(preco_custo, 2)}")

O preço de custo é: R$1.92

## **Dicionários e DataFrame**

In [ ]:
# Armazenar vários conjuntos de dados em um único objeto, o dicionário
dicionario = {
    'Nome': ["Aluno 1", "Aluno 2", "Aluno 3"],
    'Nota 1': [4.5, 9.8, 7.1],
    'Nota 2': [5.0, 8.2, 3.8],
    'Nota 3': [6.5, 8.3, 9.1]}

print(dicionario)

{'Nome': ['Aluno 1', 'Aluno 2', 'Aluno 3'], 'Nota 1': [4.5, 9.8, 7.1], 'Nota 2': [5.0, 8.2, 3.8], 'Nota 3': [6.5, 8.3, 9.1]}

In [ ]:
# Importar uma biblioteca para trabalhar com DataFrames
import pandas as pd

# Converter o dicionário em um DataFrame

df = pd.DataFrame(dicionario)

df.head()
#print(df)

      Nome  Nota 1  Nota 2  Nota 3
0  Aluno 1     4.5     5.0     6.5
1  Aluno 2     9.8     8.2     8.3
2  Aluno 3     7.1     3.8     9.1

In [ ]:
# Inserir uma nova coluna no df com o valor das médias

df["Médias"] = (df["Nota 1"] + df["Nota 2"] + df["Nota 3"]) / 3
df["Médias"] = round(df["Médias"], 1)

df.head()

      Nome  Nota 1  Nota 2  Nota 3  Médias
0  Aluno 1     4.5     5.0     6.5     5.3
1  Aluno 2     9.8     8.2     8.3     8.8
2  Aluno 3     7.1     3.8     9.1     6.7

In [ ]:
import numpy as np

media_n3 = np.mean(df['Nota 3'])

print(f"A médias das Notas 3 é: {media_n3}")
#print(f"A tabela é: \n\n {df}")

A médias das Notas 3 é: 7.966666666666666

## **Importandos dados externos**

In [ ]:
import pandas as pd

df_bcd = pd.read_excel("Dados_CalourosBCD.xlsx")

df_bcd.describe()
#df_bcd.info()
#df_bcd.head(30)

,ID,Você já morou em quantas cidades diferentes?,Como você avalia seu conhecimento em Matemática?,Data de nascimento:,Como você avalia seu cuidado com sua alimentação?,Quantos livros você leu no último ano?,Quantos idiomas você fala?
count,56.000000,56.000000,56.000000,56,56.000000,56.000000,56.000000
mean,28.500000,1.785714,6.660714,2004-07-01 10:17:08.571428608,6.571429,3.821429,1.750000
min,1.000000,0.000000,3.000000,1975-03-18 00:00:00,2.000000,0.000000,0.000000
25%,14.750000,1.000000,6.000000,2003-02-24 18:00:00,5.000000,1.000000,1.000000
50%,28.500000,1.000000,7.000000,2006-10-10 12:00:00,7.000000,2.000000,2.000000
75%,42.250000,2.000000,7.000000,2008-01-01 18:00:00,8.000000,4.250000,2.000000
max,56.000000,9.000000,10.000000,2026-12-16 00:00:00,10.000000,35.000000,3.000000
std,16.309506,1.670213,1.352127,NaN,1.961976,6.258397,0.719848

In [ ]:
media_cidades = np.mean(df_bcd['Você já morou em quantas cidades diferentes?'])
std_cidades = np.std(df_bcd['Você já morou em quantas cidades diferentes?'])

print(media_cidades)
print(std_cidades)

1.7857142857142858
1.6552328894652097

# **Medidas de Posição**

In [ ]:
# Importar as bibliotecas
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("[Estatistica-BCD]_DadosTratados_CalourosBCD_turmA.xlsx",
                   sheet_name="DadosTratados2")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 43 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                56 non-null     int64
 1   Semestre          56 non-null     object
 2   Cidade_Origem     56 non-null     object
 3   Estado_Origem     56 non-null     object
 4   Cidade_Reside     56 non-null     object
 5   Qtade_moradias    56 non-null     int64
 6   Programacao       56 non-null     object
 7   Python            56 non-null     object
 8   Python_N          56 non-null     int64
 9   R                 56 non-null     object
 10  R_N               56 non-null     int64
 11  Java              56 non-null     object
 12  Java_N            56 non-null     int64
 13  SQL               56 non-null     object
 14  SQL_N             56 non-null     int64
 15  Outras_Ling       56 non-null     object
 16  Outras_Ling_N     56 non-null     int64
 17  Matematica        56 non-null     object
 18  Nivel_Mat         56 non-null     int64
 19  Nascimento        56 non-null     datetime64[ns]
 20  Idade             55 non-null     float64
 21  Estudo_Extra      56 non-null     object
 22  Trabalha          56 non-null     object
 23  Trabalha_N        56 non-null     int64
 24  Redes_Sociais     56 non-null     object
 25  Atividade_Fisica  56 non-null     object
 26  Alimentacao       56 non-null     int64
 27  Pets              56 non-null     object
 28  Leituras          56 non-null     int64
 29  Idiomas           56 non-null     int64
 30  Modo_Trab         56 non-null     object
 31  Oportunidades     56 non-null     int64
 32  Tecnologia        56 non-null     int64
 33  Inovacao          56 non-null     int64
 34  Mat_Est           56 non-null     int64
 35  Transicao         56 non-null     int64
 36  Outros_Motivos    56 non-null     int64
 37  IA                56 non-null     int64
 38  AD                56 non-null     int64
 39  Negocios          56 non-null     int64
 40  Tecnologia2       56 non-null     int64
 41  Pesquisa          56 non-null     int64
 42  NaoSei            56 non-null     int64
dtypes: datetime64[ns](1), float64(1), int64(24), object(17)
memory usage: 18.9+ KB

In [ ]:
# Seleção da variável analisada
idade = df['Idade']
trabalho = df['Modo_Trab']

# Média Artirmética Simples
media_aritmetica1 = idade.mean()
media_aritmetica2 = np.mean(idade)

# Média Ponderada
notas = [6.5, 7.0, 8.1]
pesos = [0.1, 0.4, 0.5]
media_ponderada = np.average(notas, weights=pesos)

# Média Aparada
from scipy.stats import trim_mean
media_aparada = trim_mean(idade, 0.2)

# Mediana
mediana1 = np.median(idade)
mediana2 = np.nanmedian(idade)

# Moda
import statistics
valores = [1, 1, 2, 3, 4, 4, 5]

moda1 = statistics.mode(trabalho)
moda2 = trabalho.mode()
moda_multi = statistics.multimode(valores)


# Imprimir Resultados
print(f'Média ponderada = {media_ponderada:.2f}')
print(f'Média aritmética = {media_aritmetica2:.2f}')
print(f'Média aparada = {media_aparada:.2f}')
print(f'Mediana = {mediana2:.2f}')
print(f'Moda = {moda1}')
print(f'Moda Multimodal = {moda_multi}')

Média ponderada = 7.50
Média aritmética = 21.58
Média aparada = 19.56
Mediana = 19.00
Moda = Ambos
Moda Multimodal = [1, 4]

# **Medidas de Dispersão**

In [ ]:
# Importar bibliotecas
import pandas as pd
import numpy as np

In [ ]:
# Carregar os dados

df = pd.read_excel("[Estatistica-BCD]_DadosTratados_CalourosBCD_turmA.xlsx",
                   sheet_name="DadosTratados2")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 43 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                56 non-null     int64
 1   Semestre          56 non-null     object
 2   Cidade_Origem     56 non-null     object
 3   Estado_Origem     56 non-null     object
 4   Cidade_Reside     56 non-null     object
 5   Qtade_moradias    56 non-null     int64
 6   Programacao       56 non-null     object
 7   Python            56 non-null     object
 8   Python_N          56 non-null     int64
 9   R                 56 non-null     object
 10  R_N               56 non-null     int64
 11  Java              56 non-null     object
 12  Java_N            56 non-null     int64
 13  SQL               56 non-null     object
 14  SQL_N             56 non-null     int64
 15  Outras_Ling       56 non-null     object
 16  Outras_Ling_N     56 non-null     int64
 17  Matematica        56 non-null     object
 18  Nivel_Mat         56 non-null     int64
 19  Nascimento        56 non-null     datetime64[ns]
 20  Idade             55 non-null     float64
 21  Estudo_Extra      56 non-null     object
 22  Trabalha          56 non-null     object
 23  Trabalha_N        56 non-null     int64
 24  Redes_Sociais     56 non-null     object
 25  Atividade_Fisica  56 non-null     object
 26  Alimentacao       56 non-null     int64
 27  Pets              56 non-null     object
 28  Leituras          56 non-null     int64
 29  Idiomas           56 non-null     int64
 30  Modo_Trab         56 non-null     object
 31  Oportunidades     56 non-null     int64
 32  Tecnologia        56 non-null     int64
 33  Inovacao          56 non-null     int64
 34  Mat_Est           56 non-null     int64
 35  Transicao         56 non-null     int64
 36  Outros_Motivos    56 non-null     int64
 37  IA                56 non-null     int64
 38  AD                56 non-null     int64
 39  Negocios          56 non-null     int64
 40  Tecnologia2       56 non-null     int64
 41  Pesquisa          56 non-null     int64
 42  NaoSei            56 non-null     int64
dtypes: datetime64[ns](1), float64(1), int64(24), object(17)
memory usage: 18.9+ KB

In [ ]:
# Selecionar variáveis
idades_outras = df[df['Cidade_Origem'] != 'Blumenau']['Idade'].tolist()

idades_bnu = df[df['Cidade_Origem'] == 'Blumenau']['Idade'].tolist()

print(idades_outras)
print(idades_bnu)

[19.0, 20.0, 18.0, 20.0, 19.0, 18.0, 19.0, 18.0, 18.0, 18.0, 18.0, 31.0, 20.0, 25.0, 26.0, 18.0, 20.0, 25.0, 18.0, 19.0, 18.0, 20.0, 18.0, 20.0, 23.0, 18.0, 29.0, 17.0, 18.0, 22.0, 21.0, 28.0]
[26.0, 19.0, 19.0, 18.0, 18.0, 26.0, 51.0, 17.0, 24.0, 18.0, 17.0, 31.0, 18.0, nan, 17.0, 17.0, 18.0, 17.0, 51.0, 33.0, 21.0, 17.0, 18.0, 17.0]

In [ ]:
########################################
#### Calculo de medidas de posição #####
########################################

# Amplitude total
amp_outras = np.max(idades_outras)-np.min(idades_outras)
amp_bnu = np.nanmax(idades_bnu)-np.nanmin(idades_bnu)

# Desvio médio
mae_outras = np.mean(np.abs(idades_outras - np.mean(idades_outras)))
mae_bnu = np.nanmean(np.abs(idades_bnu - np.nanmean(idades_bnu)))

# Variância
var_outras = np.var(idades_outras, ddof=1)
var_bnu = np.nanvar(idades_bnu, ddof=1)

# Desvio padrão
std_outras = np.std(idades_outras, ddof=1)
std_bnu = np.nanstd(idades_bnu, ddof=1)

# Coeficiente de variação
cv_outras = (std_outras/np.mean(idades_outras))*100
cv_bnu = (std_bnu/np.nanmean(idades_bnu))*100


# Imprimir resultados
print(f'Média (outras cidades) = {np.mean(idades_outras):.2f}')
print(f'Média (Blumenau) = {np.nanmean(idades_bnu):.2f}\n')
print(f'Amplitude (outras cidades) = {amp_outras}')
print(f'Amplitude (Blumenau) = {amp_bnu}\n')
print(f'Desvio médio (outras cidades) = {mae_outras:.2f}')
print(f'Desvio médio (Blumenau) = {mae_bnu:.2f}\n')
print(f'Variância (outras cidades) = {var_outras:.2f}')
print(f'Variância (Blumenau) = {var_bnu:.2f}\n')
print(f'DesvPad (outras cidades) = {std_outras:.2f}')
print(f'DesvPad (Blumenau) = {std_bnu:.2f}\n')
print(f'CV (outras cidades) = {cv_outras:.1f}')
print(f'CV (Blumenau) = {cv_bnu:.1f}')

Média (outras cidades) = 20.59
Média (Blumenau) = 22.96

Amplitude (outras cidades) = 14.0
Amplitude (Blumenau) = 34.0

Desvio médio (outras cidades) = 2.79
Desvio médio (Blumenau) = 7.07

Variância (outras cidades) = 13.41
Variância (Blumenau) = 99.50

DesvPad (outras cidades) = 3.66
DesvPad (Blumenau) = 9.97

CV (outras cidades) = 17.8
CV (Blumenau) = 43.5